language: python
python:
  - "2.7"

# Global variables
env:
  global:
    - TOOLS_DIR=$HOME/build_tools
    - GNAT_ARM_BIN_PATH=$TOOLS_DIR/gnat-community-2018-arm-elf-bin
    - INSTALL_CONTROL_SCRIPT=$PWD/scripts/GNAT_CE_2018_install_control.qs

os:
  - linux

# Cache directory that allows us to not download GNAT GPL every time, speeding
# up the process.
cache:
  directories:
  - $HOME/build_tools

install:
  # Check if the GNAT package is already available in the cache directory. If
  # not, download it.
  - test -f $GNAT_ARM_BIN_PATH ||( mkdir -p $TOOLS_DIR &&  wget http://mirrors.cdn.adacore.com/art/5b0c1227a3f5d7097625478d -O $GNAT_ARM_BIN_PATH)

  - wget https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_package.sh
  - wget https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_script.qs

  - sh install_package.sh $GNAT_ARM_BIN_PATH $TOOLS_DIR/arm-elf/

  # Add GNAT to $PATH
  - export PATH=$PATH:$TOOLS_DIR/arm-elf/bin/

script:
  # Show GNAT version for the record
  - $TOOLS_DIR/arm-elf/bin/gprbuild --version

  # Build
  - $TOOLS_DIR/arm-elf/bin/gprbuild -j0 -P cf_ada_spark.gpr
